name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  flake:
    runs-on: nixos-runner
    steps:
      - uses: actions/checkout@v6
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: nix --experimental-features 'nix-command flakes' build

      - name: Build Docker
        env:
          SQLX_OFFLINE: true
        run: nix --experimental-features 'nix-command flakes' build '#docker'
