name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  docker_push:
    name: "Push docker image"
    uses: "philipcristiano/workflows/.github/workflows/docker-build-push.yml@main"
    needs: [flake, rust, atlas]
    with:
      repository: ${{ github.repository }}
      timeout: 25

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  atlas:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: et
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Create dummy tailwind file
        run: touch tailwind/tailwind.css

      - name: Apply Schema
        uses: docker://arigaio/atlas:0.21.0-community
        env:
          SKIP_TAILWIND: true
          DATABASE_URL: "postgres://postgres:postgres@postgres/et?sslmode=disable"
        with:
          args: schema apply --env local --auto-approve

      - name: sqlx check
        run: cargo install sqlx-cli && cargo sqlx prepare --check
        # uses: docker://arigaio/atlas:0.16.0-community
        env:
          SKIP_TAILWIND: true
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/et?sslmode=disable"

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"
    with:
      setup_script: |
          curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -o tailwindcss
          chmod +x tailwindcss
          mv tailwindcss /usr/local/bin

  release-please:
    needs: [flake, rust, atlas]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          release-type: rust

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        unset DATABASE_URL
        cargo build
